name: CI

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and deploy
      env:
        CI_GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
      run: |
        mkdir ~/.m2
        echo "<settings><servers><server><id>github</id><username>continuousintegration-oviva</username><password>${CI_GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
        mvn clean deploy
